version: "3.7"

services:
  samba:
    container_name: docker-samba
    image: docker-samba:latest
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - ./smb.conf:/etc/samba/smb.conf
      - /media/datos/datos:/mnt/datos