---
    version: "3.7"
    services:
      transmission:
        image: ghcr.io/linuxserver/transmission
        container_name: transmission
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
          - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
        volumes:
          - /media/datos/volumes/trasmission/config:/config
          - /media/datos/datos/download:/downloads
          - /media/datos/volumes/trasmission/config/watch:/watch
        ports:
          - 9091:9091
          - 51413:51413
          - 51413:51413/udp
        restart: unless-stopped