version: "3.7"

services:
  prometheus-server:
    container_name: prometheus-server
    image: prom/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - /media/volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
