version: "3.7"

services:
  prometheus-server:
    container_name: prometheus-server
    image: prom/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - /media/datos/volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  node-exporter:
    image: prom/node-exporter
    restart: unless-stopped
    ports:
      - '9100:9100'