name: Docker Compose Actions Workflow for pihole folder
on:
  push:
  workflow_dispatch:
    paths:
    - pihole/**
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: down
      continue-on-error: true
      working-directory: ./pihole
      run: docker-compose down
    - name: up
      working-directory: ./pihole
      run: docker-compose up -d --build
