name: Docker Compose Actions Workflow for pihole folder
on: 
  push:
    on:
      paths:
      - 'pihole/**'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: run
        run: docker-compose up -d
