name: Docker Compose Actions Workflow for pihole folder
on: 
  push:
    on:
      paths:
      - 'pihole/**
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
