name: Docker Compose Actions Workflow for trasmission folder
on:
  push:
    paths:
    - trasmission/**
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: down
      continue-on-error: true
      working-directory: ./trasmission
      run: docker-compose down
    - name: up
      working-directory: ./trasmission
      run: docker-compose up -d